# AI英语学习平台配置文件

server:
  port: "8080"
  mode: "debug" # debug, release, test

database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "" # 建议通过环境变量 DB_PASSWORD 设置
  dbname: "ai_english_learning"
  charset: "utf8mb4"

jwt:
  secret: "" # 建议通过环境变量 JWT_SECRET 设置
  access_token_ttl: 3600 # 1小时
  refresh_token_ttl: 604800 # 7天

redis:
  host: "localhost"
  port: "6379"
  password: "" # 建议通过环境变量 REDIS_PASSWORD 设置
  db: 0

app:
  name: "AI English Learning"
  version: "1.0.0"
  environment: "development" # development, staging, production
  log_level: "info" # debug, info, warn, error

log:
  level: "info" # debug, info, warn, error, fatal, panic
  format: "json" # json, text
  output: "both" # console, file, both
  file_path: "./logs/app.log"
  max_size: 100 # MB
  max_backups: 10
  max_age: 30 # days
  compress: true